sections:
  coming_soon_messages:
    display: 'Coming soon messages'
    fields:
      -
        handle: enable_messages
        field:
          inline: false
          display: 'Enable messages'
          type: checkboxes
          icon: checkboxes
          listable: hidden
          options:
            blog-card: Blog
            projects-card: Projects
      -
        handle: blog_message_text
        field:
          input_type: text
          display: 'Blog – Message text'
          type: text
          icon: text
          listable: hidden
      -
        handle: projects_message_text
        field:
          input_type: text
          display: 'Projects – Message text'
          type: text
          icon: text
          listable: hidden
  navigation_settings:
    display: 'Navigation settings'
    fields:
      -
        handle: toggle_items
        field:
          inline: true
          options:
            Home: Home
            Projects: Projects
            Blog: Blog
            Contact: Contact
          display: 'Toggle items'
          type: checkboxes
          icon: checkboxes
          listable: hidden
